"""create file  table

Revision ID: 2c643dc4b7d0
Revises: 5421a7c8d9e7
Create Date: 2026-05-04 12:28:01.257088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c643dc4b7d0'
down_revision: Union[str, Sequence[str], None] = '5421a7c8d9e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_chat_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('chat_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('unique_generated_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('files_chat_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('file_id', name=op.f('files_pkey')),
    sa.UniqueConstraint('unique_generated_name', name=op.f('files_unique_generated_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_files_chat_id'), 'files', ['chat_id'], unique=False)
    # ### end Alembic commands ###
