"""create chats table

Revision ID: 5421a7c8d9e7
Revises: 5968bee5cfe8
Create Date: 2026-05-04 11:24:23.880127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5421a7c8d9e7'
down_revision: Union[str, Sequence[str], None] = '5968bee5cfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chats', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('chats', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'id',
               existing_type=sa.String(length=36),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_column('chats', 'updated_at')
    op.drop_column('chats', 'created_at')
    # ### end Alembic commands ###
