"""added title and summary 

Revision ID: e9b62b1a920f
Revises: 74bc2a577c42
Create Date: 2026-05-16 06:38:07.010486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9b62b1a920f'
down_revision: Union[str, Sequence[str], None] = '74bc2a577c42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('title', sa.String(), nullable=True))
    op.add_column('files', sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'summary')
    op.drop_column('files', 'title')
    # ### end Alembic commands ###
